### ISSUE TITLE
ImportError: No module named urls

### ISSUE THREAD

**Issue by erikcw** [playfire/django-debug-toolbar-user-panel#19]
With django_debug_toolbar 1.2.1 and Django 1.7 I get the following exception:

```
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/erik/.virtualenvs/proj/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/Users/erik/.virtualenvs/proj/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute
    django.setup()
  File "/Users/erik/.virtualenvs/proj/lib/python2.7/site-packages/django/__init__.py", line 21, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/erik/.virtualenvs/proj/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/Users/erik/.virtualenvs/proj/lib/python2.7/site-packages/django/apps/config.py", line 197, in import_models
    self.models_module = import_module(models_module_name)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/erik/.virtualenvs/proj/src/django-debug-toolbar-user-panel/debug_toolbar_user_panel/models.py", line 1, in <module>
    import debug_toolbar.urls
ImportError: No module named urls
```

According to the [debug toolbar changelog](http://django-debug-toolbar.readthedocs.org/en/1.2/changes.html) -- version 1.0 brought some changes that required tweaks from third party panels.

**Comment by jayvdb** [comment]
Removing debug_toolbar_user_panel/models.py does the trick
